---

- name: 'Run playbook-install_k3s.yml'
  ansible.builtin.import_playbook: playbook-install_k3s.yml

- name: 'Run playbook-minio_operator.yml'
  ansible.builtin.import_playbook: playbook-minio_operator.yml
